In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Environment setup complete. Libraries imported successfully.")

Environment setup complete. Libraries imported successfully.

In [2]:
# We will load the Data Set 
df= pd.read_csv(r'C:\Users\HIMANSHU VYAS\Desktop\consumer-complaint-intelligence\data\raw_data\complaints.csv',nrows=200_000)
print("Data loaded successfully. DataFrame shape:", df.shape)

Data loaded successfully. DataFrame shape: (200000, 16)

C:\Users\HIMANSHU VYAS\AppData\Local\Temp\ipykernel_10340\2194153390.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv(r'C:\Users\HIMANSHU VYAS\Desktop\consumer-complaint-intelligence\data\raw_data\complaints.csv',nrows=200_000)

In [4]:
print("First 5 rows of the DataFrame:")
df.head()

First 5 rows of the DataFrame:

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2024-07-22,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CT,06053,NaN,Web,2024-07-22,Closed with non-monetary relief,Yes,9584621
1,2024-07-22,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,NaN,NaN,"EQUIFAX, INC.",CT,06053,NaN,Web,2024-07-22,Closed with explanation,Yes,9580257
2,2024-07-22,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,CT,06053,NaN,Web,2024-07-22,Closed with non-monetary relief,Yes,9584634
3,2024-09-03,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Credit inquiries on your report that you don't...,NaN,NaN,"EQUIFAX, INC.",CT,06053,NaN,Web,2024-09-03,Closed with explanation,Yes,9999666
4,2024-09-03,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Account status incorrect,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CT,06053,NaN,Web,2024-09-03,Closed with non-monetary relief,Yes,9995854

In [5]:
# we will see the columns of the data set
df.columns.tolist()

['Date received',
 'Product',
 'Sub-product',
 'Issue',
 'Sub-issue',
 'Consumer complaint narrative',
 'Company public response',
 'Company',
 'State',
 'ZIP code',
 'Tags',
 'Submitted via',
 'Date sent to company',
 'Company response to consumer',
 'Timely response?',
 'Complaint ID']

In [6]:
# checking the information of the data set
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Date received                 200000 non-null  object
 1   Product                       200000 non-null  object
 2   Sub-product                   199999 non-null  object
 3   Issue                         200000 non-null  object
 4   Sub-issue                     197356 non-null  object
 5   Consumer complaint narrative  3770 non-null    object
 6   Company public response       68867 non-null   object
 7   Company                       200000 non-null  object
 8   State                         199787 non-null  object
 9   ZIP code                      199819 non-null  object
 10  Tags                          5162 non-null    object
 11  Submitted via                 200000 non-null  object
 12  Date sent to company          200000 non-null  object
 13  Company response to consumer  200000 non-null  object
 14  Timely response?              200000 non-null  object
 15  Complaint ID                  200000 non-null  int64
dtypes: int64(1), object(15)
memory usage: 24.4+ MB

In [9]:
# Checking for missing values in the dataset
df.isnull().sum().sort_values(ascending=False)

Consumer complaint narrative    196230
Tags                            194838
Company public response         131133
Sub-issue                         2644
State                              213
ZIP code                           181
Sub-product                          1
Date received                        0
Product                              0
Issue                                0
Company                              0
Submitted via                        0
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Complaint ID                         0
dtype: int64

In [10]:
drop_columns = ["Tags", "ZIP code"] # tags are not useful , zip is also droping becoz we alreday have state information

In [11]:
# checking for the duplicates in the data set
df.duplicated().sum()

0

In [12]:
# max and min date 
df["Date received"].min(), df["Date received"].max()

('2014-03-25', '2026-08-16')

In [13]:
# for timely response we will check the number
df["Timely response?"].value_counts(dropna=False)

Timely response?
Yes    198966
No       1034
Name: count, dtype: int64

In [14]:
# for Issue 
df["Issue"].value_counts().head(20)

Issue
Incorrect information on your report                               109665
Problem with a company's investigation into an existing problem     36928
Improper use of your report                                         33623
Attempts to collect debt not owed                                    3316
Managing an account                                                  1922
Took or threatened to take negative or legal action                  1483
Written notification about debt                                      1261
Problem with a purchase shown on your statement                      1126
False statements or representation                                    734
Trouble during payment process                                        604
Problem with fraud alerts or security freezes                         577
Unable to get your credit report or credit score                      538
Closing an account                                                    445
Problem with a lender or other company charging your account          440
Dealing with your lender or servicer                                  426
Struggling to pay mortgage                                            384
Fraud or scam                                                         382
Other features, terms, or problems                                    378
Fees or interest                                                      359
Getting a credit card                                                 355
Name: count, dtype: int64

In [15]:
# for product 
df["Product"].value_counts()

Product
Credit reporting or other personal consumer reports                             181177
Debt collection                                                                   7280
Checking or savings account                                                       3233
Credit card                                                                       3223
Mortgage                                                                          1263
Money transfer, virtual currency, or money service                                1246
Vehicle loan or lease                                                              865
Payday loan, title loan, personal loan, or advance loan                            680
Student loan                                                                       653
Prepaid card                                                                       200
Debt or credit management                                                          163
Credit reporting, credit repair services, or other personal consumer reports        12
Money transfers                                                                      4
Credit card or prepaid card                                                          1
Name: count, dtype: int64

In [18]:
df["Submitted via"].value_counts()

Submitted via
Web            198835
Phone             564
Referral          393
Postal mail       208
Name: count, dtype: int64

In [17]:
df["Company response to consumer"].value_counts()

Company response to consumer
In progress                        85443
Closed with explanation            69863
Closed with non-monetary relief    43003
Closed with monetary relief          891
Untimely response                    800
Name: count, dtype: int64

In [1]:
# We will select the columns 
selected_columns = [
    "Date received",
    "Product",
    "Sub-product",
    "Issue",
    "Sub-issue",
    "Consumer complaint narrative",
    "Company public response",
    "Company",
    "State",
    "Submitted via",
    "Date sent to company",
    "Company response to consumer",
    "Timely response?",
    "Complaint ID"
]

len(selected_columns)

14

# We will Work on the 250k Processed Data

In [21]:
import pandas as pd 
processed_file = "../data/processed/complaints_processed_test.csv"
df_test = pd.read_csv(
    processed_file,
    parse_dates=["Date received", "Date sent to company"]
)

print("Shape:", df_test.shape)

Shape: (250000, 14)

In [5]:
df_test.columns.tolist()

['Date received',
 'Product',
 'Sub-product',
 'Issue',
 'Sub-issue',
 'Consumer complaint narrative',
 'Company public response',
 'Company',
 'State',
 'Submitted via',
 'Date sent to company',
 'Company response to consumer',
 'Timely response?',
 'Complaint ID']

In [6]:
print("Duplicates in the processed test dataset:", df_test.duplicated().sum())

Duplicates in the processed test dataset: 0

In [7]:
print('Missing values in the processed test dataset:', df_test.isnull().sum())

Missing values in the processed test dataset: Date received                        0
Product                              0
Sub-product                          1
Issue                                0
Sub-issue                         3189
Consumer complaint narrative    244809
Company public response         165902
Company                              0
State                              262
Submitted via                        0
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Complaint ID                         0
dtype: int64

In [8]:
print("Minimum date:", df_test["Date received"].min())
print("Maximum date:", df_test["Date received"].max())

Minimum date: 2014-03-25
Maximum date: 2026-08-16

In [9]:
# We willl see the % od missing value 
missing = df_test.isnull().sum()
missing_percent = (missing / len(df_test)) * 100

missing_summary = pd.DataFrame({
    "Missing Count": missing,
    "Missing %": missing_percent.round(2)
})

missing_summary.sort_values("Missing %", ascending=False)

                              Missing Count  Missing %
Consumer complaint narrative         244809      97.92
Company public response              165902      66.36
Sub-issue                              3189       1.28
State                                   262       0.10
Date received                             0       0.00
Product                                   0       0.00
Sub-product                               1       0.00
Issue                                     0       0.00
Company                                   0       0.00
Submitted via                             0       0.00
Date sent to company                      0       0.00
Company response to consumer              0       0.00
Timely response?                          0       0.00
Complaint ID                              0       0.00

In [10]:
# We will check how many narrative we have 
print(
    "Narratives available:",
    df_test["Consumer complaint narrative"].notna().sum()
)

print(
    "Narratives available %:",
    df_test["Consumer complaint narrative"].notna().mean() * 100
)

Narratives available: 5191
Narratives available %: 2.0764

In [14]:
# Also Public Response
print(
    "Public responses available:",
    df_test["Company public response"].notna().sum()
)

print(
    "Public responses available %:",
    df_test["Company public response"].notna().mean() * 100
)

Public responses available: 84098
Public responses available %: 33.6392

In [12]:
# Categorical Missing Values
categorical_missing = [
    "Sub-product",
    "Sub-issue",
    "State"
]

for col in categorical_missing:
    df_test[col] = df_test[col].fillna("Unknown")

In [13]:
df_test[categorical_missing].isnull().sum()

Sub-product    0
Sub-issue      0
State          0
dtype: int64

In [15]:
# new feature adding 
df_test["has_narrative"] = (
    df_test["Consumer complaint narrative"].notna().astype(int)
)

df_test["has_public_response"] = (
    df_test["Company public response"].notna().astype(int)
)

In [16]:
print(df_test["has_narrative"].value_counts())

has_narrative
0    244809
1      5191
Name: count, dtype: int64

In [17]:
print(df_test["has_public_response"].value_counts())

has_public_response
0    165902
1     84098
Name: count, dtype: int64

In [18]:
# We are chceking the duplicates 
print("Total complaints:", df_test["Complaint ID"].count())
print("Unique Complaint IDs:", df_test["Complaint ID"].nunique())

Total complaints: 250000
Unique Complaint IDs: 250000

In [19]:
duplicate_ids = df_test["Complaint ID"].duplicated().sum()

print("Duplicate Complaint IDs:", duplicate_ids)

Duplicate Complaint IDs: 0

In [22]:
# Date time Validation 
print(df_test[["Date received", "Date sent to company"]].dtypes)

Date received           datetime64[ns]
Date sent to company    datetime64[ns]
dtype: object

In [23]:
print("Date received:")
print(df_test["Date received"].min())
print(df_test["Date received"].max())

print("\nDate sent to company:")
print(df_test["Date sent to company"].min())
print(df_test["Date sent to company"].max())

Date received:
2014-03-25 00:00:00
2026-08-16 00:00:00

Date sent to company:
2014-04-22 00:00:00
2026-08-16 00:00:00

In [25]:
# product 
df_test['Product'].value_counts()

Product
Credit reporting or other personal consumer reports                             226384
Debt collection                                                                   9616
Checking or savings account                                                       3951
Credit card                                                                       3911
Mortgage                                                                          1537
Money transfer, virtual currency, or money service                                1474
Vehicle loan or lease                                                             1048
Payday loan, title loan, personal loan, or advance loan                            832
Student loan                                                                       789
Prepaid card                                                                       248
Debt or credit management                                                          188
Credit reporting, credit repair services, or other personal consumer reports        17
Money transfers                                                                      4
Credit card or prepaid card                                                          1
Name: count, dtype: int64

In [26]:
# submited via
df_test['Submitted via'].value_counts()

Submitted via
Web            248557
Phone             690
Referral          504
Postal mail       249
Name: count, dtype: int64

In [27]:
# Timely response
df_test["Timely response?"].value_counts()

Timely response?
Yes    248779
No       1221
Name: count, dtype: int64

In [28]:
# Companey response to consumer
df_test["Company response to consumer"].value_counts()

Company response to consumer
In progress                        109241
Closed with explanation             87193
Closed with non-monetary relief     51554
Closed with monetary relief          1090
Untimely response                     922
Name: count, dtype: int64

In [29]:
# for issue 
print("Number of unique issues:", df_test["Issue"].nunique())

Number of unique issues: 89

In [30]:
print(df_test["Issue"].value_counts().head(20))

Issue
Incorrect information on your report                               137097
Problem with a company's investigation into an existing problem     46143
Improper use of your report                                         41962
Attempts to collect debt not owed                                    4330
Managing an account                                                  2350
Took or threatened to take negative or legal action                  2006
Written notification about debt                                      1676
Problem with a purchase shown on your statement                      1369
False statements or representation                                    985
Trouble during payment process                                        740
Problem with fraud alerts or security freezes                         716
Unable to get your credit report or credit score                      663
Problem with a lender or other company charging your account          551
Closing an account                                                    533
Dealing with your lender or servicer                                  504
Struggling to pay mortgage                                            468
Fraud or scam                                                         451
Other features, terms, or problems                                    451
Getting a credit card                                                 431
Fees or interest                                                      429
Name: count, dtype: int64

In [31]:
# Data Quality Checks
print("Missing Complaint IDs:", df_test["Complaint ID"].isna().sum())
print("Complaint ID dtype:", df_test["Complaint ID"].dtype)

Missing Complaint IDs: 0
Complaint ID dtype: int64

In [32]:
print(df_test["Complaint ID"].head())

0    9584621
1    9580257
2    9584634
3    9999666
4    9995854
Name: Complaint ID, dtype: int64

In [33]:
# Final Data Validation
import pandas as pd

processed_file = "../data/processed/complaints_processed_test.csv"

df_test = pd.read_csv(
    processed_file,
    parse_dates=[
        "Date received",
        "Date sent to company"
    ]
)

print("Dataset shape:", df_test.shape)

Dataset shape: (250000, 16)

In [34]:
print("Number of columns:", len(df_test.columns))
print("\nColumns:")
for i, col in enumerate(df_test.columns, start=1):
    print(i, col)

Number of columns: 16

Columns:
1 Date received
2 Product
3 Sub-product
4 Issue
5 Sub-issue
6 Consumer complaint narrative
7 Company public response
8 Company
9 State
10 Submitted via
11 Date sent to company
12 Company response to consumer
13 Timely response?
14 Complaint ID
15 has_narrative
16 has_public_response

In [35]:
print(
    df_test[
        ["Date received", "Date sent to company"]
    ].dtypes
)

Date received           datetime64[ns]
Date sent to company    datetime64[ns]
dtype: object

In [36]:
missing = df_test.isnull().sum()

missing_percent = (
    missing / len(df_test) * 100
).round(2)

missing_summary = pd.DataFrame({
    "Missing Count": missing,
    "Missing %": missing_percent
})

missing_summary.sort_values(
    "Missing %",
    ascending=False
)

                              Missing Count  Missing %
Consumer complaint narrative         244809      97.92
Company public response              165902      66.36
Date received                             0       0.00
Product                                   0       0.00
Sub-product                               0       0.00
Issue                                     0       0.00
Sub-issue                                 0       0.00
Company                                   0       0.00
State                                     0       0.00
Submitted via                             0       0.00
Date sent to company                      0       0.00
Company response to consumer              0       0.00
Timely response?                          0       0.00
Complaint ID                              0       0.00
has_narrative                             0       0.00
has_public_response                       0       0.00

In [37]:
categorical_columns = [
    "Sub-product",
    "Sub-issue",
    "State"
]

print(
    df_test[categorical_columns]
    .isnull()
    .sum()
)

Sub-product    0
Sub-issue      0
State          0
dtype: int64

In [38]:
print(
    df_test[
        ["has_narrative", "has_public_response"]
    ].value_counts()
)

has_narrative  has_public_response
0              0                      163052
               1                       81757
1              0                        2850
               1                        2341
Name: count, dtype: int64

In [39]:
print(
    "Complete duplicate rows:",
    df_test.duplicated().sum()
)

Complete duplicate rows: 0

In [40]:
print(
    "Duplicate Complaint IDs:",
    df_test["Complaint ID"].duplicated().sum()
)

Duplicate Complaint IDs: 0

In [41]:
print(
    "Missing Complaint IDs:",
    df_test["Complaint ID"].isna().sum()
)

print(
    "Unique Complaint IDs:",
    df_test["Complaint ID"].nunique()
)

Missing Complaint IDs: 0
Unique Complaint IDs: 250000

In [42]:
print("Date received:")
print("Minimum:", df_test["Date received"].min())
print("Maximum:", df_test["Date received"].max())

print("\nDate sent to company:")
print("Minimum:", df_test["Date sent to company"].min())
print("Maximum:", df_test["Date sent to company"].max())

Date received:
Minimum: 2014-03-25 00:00:00
Maximum: 2026-08-16 00:00:00

Date sent to company:
Minimum: 2014-04-22 00:00:00
Maximum: 2026-08-16 00:00:00

In [43]:
# Final Automated check 
print("\n" + "=" * 60)
print("FINAL VALIDATION")
print("=" * 60)

checks = {
    "16 columns": len(df_test.columns) == 16,

    "Tags removed": "Tags" not in df_test.columns,

    "ZIP code removed": "ZIP code" not in df_test.columns,

    "Date received is datetime":
        pd.api.types.is_datetime64_any_dtype(
            df_test["Date received"]
        ),

    "Date sent is datetime":
        pd.api.types.is_datetime64_any_dtype(
            df_test["Date sent to company"]
        ),

    "Sub-product no missing":
        df_test["Sub-product"].isna().sum() == 0,

    "Sub-issue no missing":
        df_test["Sub-issue"].isna().sum() == 0,

    "State no missing":
        df_test["State"].isna().sum() == 0,

    "Complaint ID no missing":
        df_test["Complaint ID"].isna().sum() == 0,

    "No duplicate Complaint IDs":
        df_test["Complaint ID"].duplicated().sum() == 0,

    "has_narrative exists":
        "has_narrative" in df_test.columns,

    "has_public_response exists":
        "has_public_response" in df_test.columns
}

for check, result in checks.items():
    print(f"{'✅' if result else '❌'} {check}")

print("=" * 60)

if all(checks.values()):
    print("🎉 ALL VALIDATION CHECKS PASSED!")
else:
    print("⚠️ SOME CHECKS FAILED — REVIEW BEFORE FULL PROCESSING")

============================================================
FINAL VALIDATION
============================================================
✅ 16 columns
✅ Tags removed
✅ ZIP code removed
✅ Date received is datetime
✅ Date sent is datetime
✅ Sub-product no missing
✅ Sub-issue no missing
✅ State no missing
✅ Complaint ID no missing
✅ No duplicate Complaint IDs
✅ has_narrative exists
✅ has_public_response exists
============================================================
🎉 ALL VALIDATION CHECKS PASSED!